export const PROMISE_SUFFIX = '_@PROMISE@';
export const FULFILLED_SUFFIX = '_@FULFILLED@';
export const REJECTED_SUFFIX = '_@REJECTED@';

/***********************   Home   ***********************/

export const TOP_NAV_REQUEST = `ACTION_TOP_NAV${PROMISE_SUFFIX}`;
export const TOP_NAV_SUCCESS = `ACTION_TOP_NAV${FULFILLED_SUFFIX}`;
export const TOP_NAV_FAILURE = `ACTION_TOP_NAV${REJECTED_SUFFIX}`;

export const CHOICENESS_REQUEST = `ACTION_CHOICENESS${PROMISE_SUFFIX}`;
export const CHOICENESS_SUCCESS = `ACTION_CHOICENESS${FULFILLED_SUFFIX}`;
export const CHOICENESS_FAILURE = `ACTION_CHOICENESS${REJECTED_SUFFIX}`;
