export default {
  app_logo: require('./app_logo.png'),
  ic_checkbox: require('./ic_checkbox.png'),
  ic_checkbox_active: require('./ic_checkbox_active.png'),
  ic_del: require('./ic_del.png'),
  ic_mainTabBar_customization_normal: require('./ic_mainTabBar_customization_normal.png'),
  ic_mainTabBar_customization_selected: require('./ic_mainTabBar_customization_selected.png'),
  ic_mainTabBar_discover_normal: require('./ic_mainTabBar_discover_normal.png'),
  ic_mainTabBar_discover_selected: require('./ic_mainTabBar_discover_selected.png'),
  ic_mainTabBar_home_normal: require('./ic_mainTabBar_home_normal.png'),
  ic_mainTabBar_home_selected: require('./ic_mainTabBar_home_selected.png'),
  ic_mainTabBar_mine_normal: require('./ic_mainTabBar_mine_normal.png'),
  ic_mainTabBar_mine_selected: require('./ic_mainTabBar_mine_selected.png'),
  ic_mainTabBar_shopping_cart_normal: require('./ic_mainTabBar_shopping_cart_normal.png'),
  ic_mainTabBar_shopping_cart_selected: require('./ic_mainTabBar_shopping_cart_selected.png'),
  ic_nav_back_gray: require('./ic_nav_back_gray.png'),
  ic_nav_menu: require('./ic_nav_menu.png'),
};
